# Generated by Django 5.2.16 on 2026-07-17 20:29

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('address', models.CharField(help_text='Public display address', max_length=255)),
                ('operating_hours', models.JSONField(default=dict, help_text='{"mon": "09:00-18:00", ..., "sun": "closed"}')),
                ('capacity', models.PositiveIntegerField(help_text='Max items the room holds')),
                ('is_active', models.BooleanField(default=False, help_text='Approved by admin via Django Admin')),
                ('rating', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Avg of node ratings 0.00-5.00', max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('total_transactions', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managed_nodes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='NodePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='nodes/photos/')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='nodes.node')),
            ],
            options={
                'ordering': ('order', 'id'),
            },
        ),
    ]
