// Mocks generated by Mockito 5.4.6 from annotations
// in neighbor_node/test/features/nodes/presentation/bloc/register_node_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:neighbor_node/core/errors/failures.dart' as _i5;
import 'package:neighbor_node/features/nodes/domain/entities/node_detail_entity.dart'
    as _i7;
import 'package:neighbor_node/features/nodes/domain/entities/node_entity.dart'
    as _i6;
import 'package:neighbor_node/features/nodes/domain/repositories/nodes_repository.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [NodesRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockNodesRepository extends _i1.Mock implements _i3.NodesRepository {
  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.NodeEntity>>> getNearbyNodes({
    required double? lat,
    required double? lng,
    double? radiusMeters,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getNearbyNodes, [], {
              #lat: lat,
              #lng: lng,
              #radiusMeters: radiusMeters,
            }),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, List<_i6.NodeEntity>>>.value(
                  _FakeEither_0<_i5.Failure, List<_i6.NodeEntity>>(
                    this,
                    Invocation.method(#getNearbyNodes, [], {
                      #lat: lat,
                      #lng: lng,
                      #radiusMeters: radiusMeters,
                    }),
                  ),
                ),
            returnValueForMissingStub:
                _i4.Future<_i2.Either<_i5.Failure, List<_i6.NodeEntity>>>.value(
                  _FakeEither_0<_i5.Failure, List<_i6.NodeEntity>>(
                    this,
                    Invocation.method(#getNearbyNodes, [], {
                      #lat: lat,
                      #lng: lng,
                      #radiusMeters: radiusMeters,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i6.NodeEntity>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i7.NodeDetailEntity>> getNode(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getNode, [id]),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i7.NodeDetailEntity>>.value(
                  _FakeEither_0<_i5.Failure, _i7.NodeDetailEntity>(
                    this,
                    Invocation.method(#getNode, [id]),
                  ),
                ),
            returnValueForMissingStub:
                _i4.Future<_i2.Either<_i5.Failure, _i7.NodeDetailEntity>>.value(
                  _FakeEither_0<_i5.Failure, _i7.NodeDetailEntity>(
                    this,
                    Invocation.method(#getNode, [id]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i7.NodeDetailEntity>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i7.NodeDetailEntity>> registerNode({
    required String? name,
    required String? description,
    required String? address,
    required double? lat,
    required double? lng,
    required int? capacity,
    required Map<String, String>? operatingHours,
    List<String>? photoPaths,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#registerNode, [], {
              #name: name,
              #description: description,
              #address: address,
              #lat: lat,
              #lng: lng,
              #capacity: capacity,
              #operatingHours: operatingHours,
              #photoPaths: photoPaths,
            }),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i7.NodeDetailEntity>>.value(
                  _FakeEither_0<_i5.Failure, _i7.NodeDetailEntity>(
                    this,
                    Invocation.method(#registerNode, [], {
                      #name: name,
                      #description: description,
                      #address: address,
                      #lat: lat,
                      #lng: lng,
                      #capacity: capacity,
                      #operatingHours: operatingHours,
                      #photoPaths: photoPaths,
                    }),
                  ),
                ),
            returnValueForMissingStub:
                _i4.Future<_i2.Either<_i5.Failure, _i7.NodeDetailEntity>>.value(
                  _FakeEither_0<_i5.Failure, _i7.NodeDetailEntity>(
                    this,
                    Invocation.method(#registerNode, [], {
                      #name: name,
                      #description: description,
                      #address: address,
                      #lat: lat,
                      #lng: lng,
                      #capacity: capacity,
                      #operatingHours: operatingHours,
                      #photoPaths: photoPaths,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i7.NodeDetailEntity>>);

  @override
  _i4.Future<int?> getManagedNodeId() =>
      (super.noSuchMethod(
            Invocation.method(#getManagedNodeId, []),
            returnValue: _i4.Future<int?>.value(),
            returnValueForMissingStub: _i4.Future<int?>.value(),
          )
          as _i4.Future<int?>);
}
