// Mocks generated by Mockito 5.4.6 from annotations
// in neighbor_node/test/features/items/presentation/bloc/add_item_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:neighbor_node/core/errors/failures.dart' as _i5;
import 'package:neighbor_node/features/items/domain/entities/item_entity.dart'
    as _i6;
import 'package:neighbor_node/features/items/domain/repositories/items_repository.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ItemsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockItemsRepository extends _i1.Mock implements _i3.ItemsRepository {
  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.ItemEntity>> createItem({
    required String? title,
    required String? description,
    required String? category,
    required String? condition,
    required String? dailyRate,
    required String? depositAmount,
    int? nodeId,
    List<String>? imagePaths,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createItem, [], {
              #title: title,
              #description: description,
              #category: category,
              #condition: condition,
              #dailyRate: dailyRate,
              #depositAmount: depositAmount,
              #nodeId: nodeId,
              #imagePaths: imagePaths,
            }),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i6.ItemEntity>>.value(
                  _FakeEither_0<_i5.Failure, _i6.ItemEntity>(
                    this,
                    Invocation.method(#createItem, [], {
                      #title: title,
                      #description: description,
                      #category: category,
                      #condition: condition,
                      #dailyRate: dailyRate,
                      #depositAmount: depositAmount,
                      #nodeId: nodeId,
                      #imagePaths: imagePaths,
                    }),
                  ),
                ),
            returnValueForMissingStub:
                _i4.Future<_i2.Either<_i5.Failure, _i6.ItemEntity>>.value(
                  _FakeEither_0<_i5.Failure, _i6.ItemEntity>(
                    this,
                    Invocation.method(#createItem, [], {
                      #title: title,
                      #description: description,
                      #category: category,
                      #condition: condition,
                      #dailyRate: dailyRate,
                      #depositAmount: depositAmount,
                      #nodeId: nodeId,
                      #imagePaths: imagePaths,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.ItemEntity>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.ItemEntity>>> getNearbyItems({
    required double? lat,
    required double? lng,
    double? radiusMeters,
    String? category,
    double? maxRate,
    String? storageType,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getNearbyItems, [], {
              #lat: lat,
              #lng: lng,
              #radiusMeters: radiusMeters,
              #category: category,
              #maxRate: maxRate,
              #storageType: storageType,
            }),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, List<_i6.ItemEntity>>>.value(
                  _FakeEither_0<_i5.Failure, List<_i6.ItemEntity>>(
                    this,
                    Invocation.method(#getNearbyItems, [], {
                      #lat: lat,
                      #lng: lng,
                      #radiusMeters: radiusMeters,
                      #category: category,
                      #maxRate: maxRate,
                      #storageType: storageType,
                    }),
                  ),
                ),
            returnValueForMissingStub:
                _i4.Future<_i2.Either<_i5.Failure, List<_i6.ItemEntity>>>.value(
                  _FakeEither_0<_i5.Failure, List<_i6.ItemEntity>>(
                    this,
                    Invocation.method(#getNearbyItems, [], {
                      #lat: lat,
                      #lng: lng,
                      #radiusMeters: radiusMeters,
                      #category: category,
                      #maxRate: maxRate,
                      #storageType: storageType,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i6.ItemEntity>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.ItemEntity>>> getMyItems() =>
      (super.noSuchMethod(
            Invocation.method(#getMyItems, []),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, List<_i6.ItemEntity>>>.value(
                  _FakeEither_0<_i5.Failure, List<_i6.ItemEntity>>(
                    this,
                    Invocation.method(#getMyItems, []),
                  ),
                ),
            returnValueForMissingStub:
                _i4.Future<_i2.Either<_i5.Failure, List<_i6.ItemEntity>>>.value(
                  _FakeEither_0<_i5.Failure, List<_i6.ItemEntity>>(
                    this,
                    Invocation.method(#getMyItems, []),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i6.ItemEntity>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.ItemEntity>>> getNodeInventory(
    int? nodeId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getNodeInventory, [nodeId]),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, List<_i6.ItemEntity>>>.value(
                  _FakeEither_0<_i5.Failure, List<_i6.ItemEntity>>(
                    this,
                    Invocation.method(#getNodeInventory, [nodeId]),
                  ),
                ),
            returnValueForMissingStub:
                _i4.Future<_i2.Either<_i5.Failure, List<_i6.ItemEntity>>>.value(
                  _FakeEither_0<_i5.Failure, List<_i6.ItemEntity>>(
                    this,
                    Invocation.method(#getNodeInventory, [nodeId]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i6.ItemEntity>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.ItemEntity>> setItemAvailability({
    required int? itemId,
    required bool? isAvailable,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#setItemAvailability, [], {
              #itemId: itemId,
              #isAvailable: isAvailable,
            }),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i6.ItemEntity>>.value(
                  _FakeEither_0<_i5.Failure, _i6.ItemEntity>(
                    this,
                    Invocation.method(#setItemAvailability, [], {
                      #itemId: itemId,
                      #isAvailable: isAvailable,
                    }),
                  ),
                ),
            returnValueForMissingStub:
                _i4.Future<_i2.Either<_i5.Failure, _i6.ItemEntity>>.value(
                  _FakeEither_0<_i5.Failure, _i6.ItemEntity>(
                    this,
                    Invocation.method(#setItemAvailability, [], {
                      #itemId: itemId,
                      #isAvailable: isAvailable,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.ItemEntity>>);
}
