// Mocks generated by Mockito 5.4.6 from annotations
// in neighbor_node/test/features/items/presentation/bloc/donation_queue_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:neighbor_node/core/errors/failures.dart' as _i5;
import 'package:neighbor_node/features/items/domain/entities/item_detail_entity.dart'
    as _i6;
import 'package:neighbor_node/features/items/domain/entities/item_entity.dart'
    as _i7;
import 'package:neighbor_node/features/items/domain/repositories/items_repository.dart'
    as _i3;
import 'package:neighbor_node/features/nodes/domain/entities/node_detail_entity.dart'
    as _i10;
import 'package:neighbor_node/features/nodes/domain/entities/node_entity.dart'
    as _i9;
import 'package:neighbor_node/features/nodes/domain/repositories/nodes_repository.dart'
    as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ItemsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockItemsRepository extends _i1.Mock implements _i3.ItemsRepository {
  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.ItemDetailEntity>> getItem(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getItem, [id]),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i6.ItemDetailEntity>>.value(
                  _FakeEither_0<_i5.Failure, _i6.ItemDetailEntity>(
                    this,
                    Invocation.method(#getItem, [id]),
                  ),
                ),
            returnValueForMissingStub:
                _i4.Future<_i2.Either<_i5.Failure, _i6.ItemDetailEntity>>.value(
                  _FakeEither_0<_i5.Failure, _i6.ItemDetailEntity>(
                    this,
                    Invocation.method(#getItem, [id]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.ItemDetailEntity>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i7.ItemEntity>> createItem({
    required String? title,
    required String? description,
    required String? category,
    required String? condition,
    required String? dailyRate,
    required String? depositAmount,
    int? nodeId,
    List<String>? imagePaths,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createItem, [], {
              #title: title,
              #description: description,
              #category: category,
              #condition: condition,
              #dailyRate: dailyRate,
              #depositAmount: depositAmount,
              #nodeId: nodeId,
              #imagePaths: imagePaths,
            }),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i7.ItemEntity>>.value(
                  _FakeEither_0<_i5.Failure, _i7.ItemEntity>(
                    this,
                    Invocation.method(#createItem, [], {
                      #title: title,
                      #description: description,
                      #category: category,
                      #condition: condition,
                      #dailyRate: dailyRate,
                      #depositAmount: depositAmount,
                      #nodeId: nodeId,
                      #imagePaths: imagePaths,
                    }),
                  ),
                ),
            returnValueForMissingStub:
                _i4.Future<_i2.Either<_i5.Failure, _i7.ItemEntity>>.value(
                  _FakeEither_0<_i5.Failure, _i7.ItemEntity>(
                    this,
                    Invocation.method(#createItem, [], {
                      #title: title,
                      #description: description,
                      #category: category,
                      #condition: condition,
                      #dailyRate: dailyRate,
                      #depositAmount: depositAmount,
                      #nodeId: nodeId,
                      #imagePaths: imagePaths,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i7.ItemEntity>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i7.ItemEntity>>> getNearbyItems({
    required double? lat,
    required double? lng,
    double? radiusMeters,
    String? category,
    double? maxRate,
    String? storageType,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getNearbyItems, [], {
              #lat: lat,
              #lng: lng,
              #radiusMeters: radiusMeters,
              #category: category,
              #maxRate: maxRate,
              #storageType: storageType,
            }),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, List<_i7.ItemEntity>>>.value(
                  _FakeEither_0<_i5.Failure, List<_i7.ItemEntity>>(
                    this,
                    Invocation.method(#getNearbyItems, [], {
                      #lat: lat,
                      #lng: lng,
                      #radiusMeters: radiusMeters,
                      #category: category,
                      #maxRate: maxRate,
                      #storageType: storageType,
                    }),
                  ),
                ),
            returnValueForMissingStub:
                _i4.Future<_i2.Either<_i5.Failure, List<_i7.ItemEntity>>>.value(
                  _FakeEither_0<_i5.Failure, List<_i7.ItemEntity>>(
                    this,
                    Invocation.method(#getNearbyItems, [], {
                      #lat: lat,
                      #lng: lng,
                      #radiusMeters: radiusMeters,
                      #category: category,
                      #maxRate: maxRate,
                      #storageType: storageType,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i7.ItemEntity>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i7.ItemEntity>>> getMyItems() =>
      (super.noSuchMethod(
            Invocation.method(#getMyItems, []),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, List<_i7.ItemEntity>>>.value(
                  _FakeEither_0<_i5.Failure, List<_i7.ItemEntity>>(
                    this,
                    Invocation.method(#getMyItems, []),
                  ),
                ),
            returnValueForMissingStub:
                _i4.Future<_i2.Either<_i5.Failure, List<_i7.ItemEntity>>>.value(
                  _FakeEither_0<_i5.Failure, List<_i7.ItemEntity>>(
                    this,
                    Invocation.method(#getMyItems, []),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i7.ItemEntity>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i7.ItemEntity>>> getNodeInventory(
    int? nodeId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getNodeInventory, [nodeId]),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, List<_i7.ItemEntity>>>.value(
                  _FakeEither_0<_i5.Failure, List<_i7.ItemEntity>>(
                    this,
                    Invocation.method(#getNodeInventory, [nodeId]),
                  ),
                ),
            returnValueForMissingStub:
                _i4.Future<_i2.Either<_i5.Failure, List<_i7.ItemEntity>>>.value(
                  _FakeEither_0<_i5.Failure, List<_i7.ItemEntity>>(
                    this,
                    Invocation.method(#getNodeInventory, [nodeId]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i7.ItemEntity>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i7.ItemEntity>> setItemAvailability({
    required int? itemId,
    required bool? isAvailable,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#setItemAvailability, [], {
              #itemId: itemId,
              #isAvailable: isAvailable,
            }),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i7.ItemEntity>>.value(
                  _FakeEither_0<_i5.Failure, _i7.ItemEntity>(
                    this,
                    Invocation.method(#setItemAvailability, [], {
                      #itemId: itemId,
                      #isAvailable: isAvailable,
                    }),
                  ),
                ),
            returnValueForMissingStub:
                _i4.Future<_i2.Either<_i5.Failure, _i7.ItemEntity>>.value(
                  _FakeEither_0<_i5.Failure, _i7.ItemEntity>(
                    this,
                    Invocation.method(#setItemAvailability, [], {
                      #itemId: itemId,
                      #isAvailable: isAvailable,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i7.ItemEntity>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.ItemDetailEntity>>>
  getPendingDonations(int? nodeId) =>
      (super.noSuchMethod(
            Invocation.method(#getPendingDonations, [nodeId]),
            returnValue:
                _i4.Future<
                  _i2.Either<_i5.Failure, List<_i6.ItemDetailEntity>>
                >.value(
                  _FakeEither_0<_i5.Failure, List<_i6.ItemDetailEntity>>(
                    this,
                    Invocation.method(#getPendingDonations, [nodeId]),
                  ),
                ),
            returnValueForMissingStub:
                _i4.Future<
                  _i2.Either<_i5.Failure, List<_i6.ItemDetailEntity>>
                >.value(
                  _FakeEither_0<_i5.Failure, List<_i6.ItemDetailEntity>>(
                    this,
                    Invocation.method(#getPendingDonations, [nodeId]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i6.ItemDetailEntity>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.ItemDetailEntity>> reviewDonation({
    required int? itemId,
    required bool? accept,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#reviewDonation, [], {
              #itemId: itemId,
              #accept: accept,
            }),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i6.ItemDetailEntity>>.value(
                  _FakeEither_0<_i5.Failure, _i6.ItemDetailEntity>(
                    this,
                    Invocation.method(#reviewDonation, [], {
                      #itemId: itemId,
                      #accept: accept,
                    }),
                  ),
                ),
            returnValueForMissingStub:
                _i4.Future<_i2.Either<_i5.Failure, _i6.ItemDetailEntity>>.value(
                  _FakeEither_0<_i5.Failure, _i6.ItemDetailEntity>(
                    this,
                    Invocation.method(#reviewDonation, [], {
                      #itemId: itemId,
                      #accept: accept,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.ItemDetailEntity>>);
}

/// A class which mocks [NodesRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockNodesRepository extends _i1.Mock implements _i8.NodesRepository {
  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i9.NodeEntity>>> getNearbyNodes({
    required double? lat,
    required double? lng,
    double? radiusMeters,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getNearbyNodes, [], {
              #lat: lat,
              #lng: lng,
              #radiusMeters: radiusMeters,
            }),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, List<_i9.NodeEntity>>>.value(
                  _FakeEither_0<_i5.Failure, List<_i9.NodeEntity>>(
                    this,
                    Invocation.method(#getNearbyNodes, [], {
                      #lat: lat,
                      #lng: lng,
                      #radiusMeters: radiusMeters,
                    }),
                  ),
                ),
            returnValueForMissingStub:
                _i4.Future<_i2.Either<_i5.Failure, List<_i9.NodeEntity>>>.value(
                  _FakeEither_0<_i5.Failure, List<_i9.NodeEntity>>(
                    this,
                    Invocation.method(#getNearbyNodes, [], {
                      #lat: lat,
                      #lng: lng,
                      #radiusMeters: radiusMeters,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i9.NodeEntity>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i10.NodeDetailEntity>> getNode(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getNode, [id]),
            returnValue:
                _i4.Future<
                  _i2.Either<_i5.Failure, _i10.NodeDetailEntity>
                >.value(
                  _FakeEither_0<_i5.Failure, _i10.NodeDetailEntity>(
                    this,
                    Invocation.method(#getNode, [id]),
                  ),
                ),
            returnValueForMissingStub:
                _i4.Future<
                  _i2.Either<_i5.Failure, _i10.NodeDetailEntity>
                >.value(
                  _FakeEither_0<_i5.Failure, _i10.NodeDetailEntity>(
                    this,
                    Invocation.method(#getNode, [id]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i10.NodeDetailEntity>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i10.NodeDetailEntity>> registerNode({
    required String? name,
    required String? description,
    required String? address,
    required double? lat,
    required double? lng,
    required int? capacity,
    required Map<String, String>? operatingHours,
    List<String>? photoPaths,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#registerNode, [], {
              #name: name,
              #description: description,
              #address: address,
              #lat: lat,
              #lng: lng,
              #capacity: capacity,
              #operatingHours: operatingHours,
              #photoPaths: photoPaths,
            }),
            returnValue:
                _i4.Future<
                  _i2.Either<_i5.Failure, _i10.NodeDetailEntity>
                >.value(
                  _FakeEither_0<_i5.Failure, _i10.NodeDetailEntity>(
                    this,
                    Invocation.method(#registerNode, [], {
                      #name: name,
                      #description: description,
                      #address: address,
                      #lat: lat,
                      #lng: lng,
                      #capacity: capacity,
                      #operatingHours: operatingHours,
                      #photoPaths: photoPaths,
                    }),
                  ),
                ),
            returnValueForMissingStub:
                _i4.Future<
                  _i2.Either<_i5.Failure, _i10.NodeDetailEntity>
                >.value(
                  _FakeEither_0<_i5.Failure, _i10.NodeDetailEntity>(
                    this,
                    Invocation.method(#registerNode, [], {
                      #name: name,
                      #description: description,
                      #address: address,
                      #lat: lat,
                      #lng: lng,
                      #capacity: capacity,
                      #operatingHours: operatingHours,
                      #photoPaths: photoPaths,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i10.NodeDetailEntity>>);

  @override
  _i4.Future<int?> getManagedNodeId() =>
      (super.noSuchMethod(
            Invocation.method(#getManagedNodeId, []),
            returnValue: _i4.Future<int?>.value(),
            returnValueForMissingStub: _i4.Future<int?>.value(),
          )
          as _i4.Future<int?>);
}
