# Generated by Django 5.2.16 on 2026-07-18 11:11

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nodes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage_type', models.CharField(choices=[('PERSONAL', 'Personal'), ('NODE', 'Node')], max_length=10)),
                ('listing_status', models.CharField(choices=[('PENDING_DONATION', 'Pending donation'), ('ACTIVE', 'Active'), ('REJECTED', 'Rejected'), ('ARCHIVED', 'Archived')], default='ACTIVE', max_length=20)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('TOOLS', 'Tools'), ('BOOKS', 'Books'), ('ELECTRONICS', 'Electronics'), ('SPORTS', 'Sports'), ('OTHER', 'Other')], max_length=15)),
                ('condition', models.CharField(choices=[('NEW', 'New'), ('GOOD', 'Good'), ('FAIR', 'Fair'), ('POOR', 'Poor')], max_length=5)),
                ('daily_rate', models.DecimalField(decimal_places=2, help_text='PKR per day', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('deposit_amount', models.DecimalField(decimal_places=2, help_text='Security deposit, PKR', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('is_available', models.BooleanField(default=True, help_text='Toggled automatically by the transaction flow')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('node', models.ForeignKey(blank=True, help_text='Null = personal P2P item', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='nodes.node')),
                ('owner', models.ForeignKey(help_text='Original owner, even when donated', on_delete=django.db.models.deletion.CASCADE, related_name='items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ItemImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='items/images/')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='items.item')),
            ],
            options={
                'ordering': ('order', 'id'),
            },
        ),
    ]
